# Generated by Django 3.1.4 on 2021-02-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='discription',
            new_name='description',
        ),
    ]
