# Generated by Django 3.1.4 on 2021-02-14 20:46

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210212_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.FilePathField(path=projects.models.images_path),
        ),
    ]
