# Generated by Django 3.1.4 on 2021-02-14 20:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FilePathField(default='/img', path=blog.models.images_path),
        ),
    ]
