# Generated by Django 3.1.4 on 2021-02-14 20:46

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FilePathField(default='blog/img', path=blog.models.images_path),
        ),
    ]
