# Generated by Django 3.1.4 on 2021-02-14 20:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210214_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FilePathField(path=blog.models.images_path),
        ),
    ]
